#Joseph Keating code

# Function to calculate the tree distance
#
# Arguments:
#
# trees     Phylo, phylo object generated by ape or phytools which
#           should contains one tree per list
# method    Character, default is "RF" (Robinso Foulds distance)
# normalise Boolean, TRUE or FALSE, default is FAULSE

tree_dist <- function(trees, method = "RF", normalise = F)
{
  N <- length(trees)
  res <- matrix(0, N, N)
  index_m <- upper.tri(matrix(F, N, N))
  for(i in 1:(N-1)){
    row_res <- future.apply::future_lapply((i+1):N, function(j){
      t1 <- trees[[i]]
      t2 <- trees[[j]]
      #check if tip labels are the same. If not, reduce trees to compatible tip labels
      tips <- Reduce(intersect, list(t1$tip.label, t2$tip.label))
      t1 <- keep.tip(t1, tips)  #t1 <- phytools::keep.tip(t1, tips)
      t2 <- keep.tip(t2, tips)
      if(method == "RF"){
        RF.dist(t1, t2, normalize = normalise)
      }
      if(method == "quartet"){
        if(normalise){
          Q <- QuartetStatus(t1, t2)
          Q[4]/Q[2]
        } else {
          QuartetStatus(t1, t2)[[4]]
        }
      }
    }, future.seed=TRUE)
    res[i, which(index_m[i,])] <- unlist(row_res)
  }
  res <- res + t(res)
  return(res)
  
}
